#!/bin/bash

# Get random image file name
# IMG_NAME=$(find ~/Pictures/ -type f | shuf -n 1)
# full path to that random image file
IMG_PATH=$(find ~/Pictures/ -type f | shuf -n 1)
# Command to change wallpaper
swww img $IMG_PATH --transition-type center --transition-fps 144 --transition-duration 0.9
